export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_BIRTHDAYS = 'GET_BIRTHDAYS';
export const BIRTHDAY_LOADING = 'BIRTHDAY_LOADING';
export const BIRTHDAYS_NOT_FOUND = 'BIRTHDAYS_NOT_FOUND';
export const CLEAR_CURRENT_BIRTHDAY = 'CLEAR_CURRENT_BRITHDAYS';
export const GET_SINGLE_BIRTHDAY = 'GET_SINGLE_BIRTHDAY';
export const DELETE_BIRTHDAY = 'DELETE_BIRTHDAY';

// export const GET_PROFILES = 'GET_PROFILES'; I DONT THINK I'LL NEED THIS...?

// bday
export const BDAY_LOADING = 'BDAY_LOADING';
export const GET_BDAYS = 'GET_BDAYS';
export const GET_BDAY = 'GET_BDAY';
export const ADD_BDAY = 'ADD_BDAY';
export const DELETE_POST = 'DELETE_POST';
